### ISSUE TITLE
How to upload code to heroku

### ISSUE THREAD

**Issue by tiepntt** [NguyenThaiTiep/APP#14]
1.

**Comment by tiepntt** [comment]
2020-04-24T19:04:44.915004+00:00 app[web.1]: events.js:287
2020-04-24T19:04:44.915013+00:00 app[web.1]: throw er; // Unhandled 'error' event
2020-04-24T19:04:44.915014+00:00 app[web.1]: ^
2020-04-24T19:04:44.915014+00:00 app[web.1]:
2020-04-24T19:04:44.915015+00:00 app[web.1]: Error: Connection lost: The server closed the connection.
2020-04-24T19:04:44.915016+00:00 app[web.1]: at Protocol.end (/app/node_modules/mysql/lib/protocol/Protocol.js:112:13)
2020-04-24T19:04:44.915016+00:00 app[web.1]: at Socket. (/app/node_modules/mysql/lib/Connection.js:94:28)
2020-04-24T19:04:44.915017+00:00 app[web.1]: at Socket. (/app/node_modules/mysql/lib/Connection.js:526:10)
2020-04-24T19:04:44.915017+00:00 app[web.1]: at Socket.emit (events.js:322:22)
2020-04-24T19:04:44.915018+00:00 app[web.1]: at endReadableNT (_stream_readable.js:1187:12)
2020-04-24T19:04:44.915018+00:00 app[web.1]: at processTicksAndRejections (internal/process/task_queues.js:84:21)
2020-04-24T19:04:44.915019+00:00 app[web.1]: Emitted 'error' event on Connection instance at:
2020-04-24T19:04:44.915019+00:00 app[web.1]: at Connection._handleProtocolError (/app/node_modules/mysql/lib/Connection.js:423:8)
2020-04-24T19:04:44.915020+00:00 app[web.1]: at Protocol.emit (events.js:310:20)
2020-04-24T19:04:44.915020+00:00 app[web.1]: at Protocol._delegateError (/app/node_modules/mysql/lib/protocol/Protocol.js:398:10)
2020-04-24T19:04:44.915021+00:00 app[web.1]: at Protocol.end (/app/node_modules/mysql/lib/protocol/Protocol.js:116:8)
2020-04-24T19:04:44.915021+00:00 app[web.1]: at Socket. (/app/node_modules/mysql/lib/Connection.js:94:28)
2020-04-24T19:04:44.915021+00:00 app[web.1]: [... lines matching original stack trace ...]
2020-04-24T19:04:44.915022+00:00 app[web.1]: at processTicksAndRejections (internal/process/task_queues.js:84:21) {
2020-04-24T19:04:44.915022+00:00 app[web.1]: fatal: true,
2020-04-24T19:04:44.915022+00:00 app[web.1]: code: 'PROTOCOL_CONNECTION_LOST'
2020-04-24T19:04:44.915023+00:00 app[web.1]: }
2020-04-24T19:04:44.921688+00:00 app[web.1]: npm ERR! code ELIFECYCLE
2020-04-24T19:04:44.921895+00:00 app[web.1]: npm ERR! errno 1
2020-04-24T19:04:44.922773+00:00 app[web.1]: npm ERR! src@0.0.0 start: node ./bin/www
2020-04-24T19:04:44.922873+00:00 app[web.1]: npm ERR! Exit status 1
