### ISSUE TITLE
TypeError: Cannot read property 'be' of undefined

### ISSUE THREAD

**Issue by tiepntt** [NguyenThaiTiep/APP#18]
`log = console.log;
_true = () => true;
chai = require('chai');
expect = chai.expect;
should = chai.should;
assert = require('assert')
chaiAsPromised = require('chai-as-promised')
chai.use(chaiAsPromised)

_ = require('lodash');

describe('#mocha basic', () => {
    it('compare true 1 to 1', () => {
        assert.equal(1 == 1, true)

    })
    it('true should be true', () => {
        true.should.be.true;

    })
})`
` #mocha basic
    √ compare true 1 to 1
    1) true should be true

  1 passing (12ms)
  1 failing

  1) #mocha basic
       true should be true:
     TypeError: Cannot read property 'be' of undefined
      at Context.<anonymous> (test.index.js:19:21)
      at processImmediate (internal/timers.js:456:21)

npm ERR! Test failed.  See above for more details.`

**Comment by tiepntt** [comment]
sorry I write code wrong
from 👍 
`should = chai.should;`
to : 
`should = chai.should();`

**Comment by tiepntt** [comment]
done
