### ISSUE TITLE
html dom with testing by mocha

### ISSUE THREAD

**Issue by tiepntt** [NguyenThaiTiep/APP#19]
```
describe('document', () => {

    jsdom();

    it('myMove coin ', () => {

        var element = document.createElement('div');
        true.should.be.true;
    })

})
```

```
  Market Game
    √ checksum True
    √ checksum False

  hihi
    1) "before all" hook for "myMove coin "


  2 passing (542ms)
  1 failing

  1) hihi
       "before all" hook for "myMove coin ":
     Uncaught SecurityError: localStorage is not available for opaque origins
      at Window.get localStorage [as localStorage] (node_modules\jsdom\lib\jsdom\browser\Window.js:257:15)
      at propagateToGlobal (node_modules\mocha-jsdom\index.js:108:27)
      at Object.done (node_modules\mocha-jsdom\index.js:59:9)
      at C:\Users\Admin\Desktop\APP\node_modules\jsdom\lib\old-api.js:366:18
      at processTicksAndRejections (internal/process/task_queues.js:79:11)
```

**Comment by tiepntt** [comment]
Use module mocha-jsdom

``

`npm i --s mocha-jsdom`
